title: University of Sheffield Triathlon Club
email: triathlon@sheffield.ac.uk
description: Swim, bike and run with the University of Sheffield Triathlon Club.
baseurl: /uostriathlon
url: https://dhbedkb.github.io
lang: en-GB
timezone: Europe/London
markdown: kramdown
permalink: pretty
future: false

plugins:
- jekyll-sitemap
- jekyll-seo-tag

sass:
  style: compressed

exclude:
- README.md
- node_modules
- vendor
- Gemfile.lock
- package-lock.json
- bin/
- scripts/
- docs/
- oauth-worker/
- .archive/
- _site/
- .jekyll-cache/
- .sass-cache/
- .jekyll-metadata

defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
