from pathlib import Path

p = Path("assets/css/main.css")
text = p.read_text().rstrip()
lines = []
a = lines.append
a("")
a("/* =====================================================")
a("   UNIVERSAL TILE SYSTEM V1")
a("   One spacing contract for cards, widgets, media, and nested frames.")
a("   ===================================================== */")
a("")
a(":root {")
a("  --u-tile-gap: 1.5rem;")
a("  --u-tile-pad: clamp(1rem, 2.5vw, 1.5rem);")
a("  --u-tile-pad-compact: 1rem;")
a("  --u-tile-radius: 1.75rem;")
a("  --u-tile-frame-radius: 1rem;")
a("  --u-tile-border: 1px solid rgba(255, 255, 255, 0.14);")
a("  --u-tile-frame-border: 1px solid rgba(255, 255, 255, 0.12);")
a("  --u-tile-bg: rgba(255, 255, 255, 0.055);")
a("  --u-tile-frame-bg: rgba(0, 0, 0, 0.34);")
a("  --u-tile-shadow: 0 18px 50px rgba(0, 0, 0, 0.24);")
a("}")
a("")
a(".u-tile {")
a("  box-sizing: border-box;")
a("  padding: var(--u-tile-pad);")
a("  border-radius: var(--u-tile-radius);")
a("  border: var(--u-tile-border);")
a("  background: var(--u-tile-bg);")
a("  box-shadow: var(--u-tile-shadow);")
a("  overflow: hidden;")
a("}")
a("")
a(".u-tile-head {")
a("  margin: 0 0 var(--u-tile-pad-compact);")
a("}")
a("")
a(".u-tile-head > :first-child {")
a("  margin-top: 0;")
a("}")
a("")
a(".u-tile-head > :last-child {")
a("  margin-bottom: 0;")
a("}")
a("")
a(".u-tile-frame {")
a("  box-sizing: border-box;")
a("  width: fit-content;")
a("  max-width: 100%;")
a("  margin-inline: auto;")
a("  padding: var(--u-tile-pad-compact);")
a("  border-radius: var(--u-tile-frame-radius);")
a("  border: var(--u-tile-frame-border);")
a("  background: var(--u-tile-frame-bg);")
a("  overflow: hidden;")
a("  line-height: 0;")
a("}")
a("")
a(".u-tile-frame > iframe,")
a(".u-tile-frame > img,")
a(".u-tile-frame > video {")
a("  display: block;")
a("  max-width: 100%;")
a("  margin: 0;")
a("  border: 0;")
a("}")
