from pathlib import Path

p = Path("assets/css/main.css")
text = p.read_text().rstrip()

marker = "/* =====================================================\n   UNIVERSAL TILE SYSTEM V1"

if marker in text:
    print("UNIVERSAL TILE SYSTEM V1 already exists.")
    raise SystemExit

gt = chr(62)
lines = []
a = lines.append
a("")
a("/* =====================================================")
a("   UNIVERSAL TILE SYSTEM V1")
a("   Shared tile spacing contract across cards, widgets, and media.")
a("   ===================================================== */")
a("")
a(":root {")
a("  --u-tile-gap: 1.5rem;")
a("  --u-tile-pad: clamp(1rem, 2.5vw, 1.5rem);")
a("  --u-tile-pad-compact: 1rem;")
a("  --u-tile-radius: 1.75rem;")
a("  --u-tile-frame-radius: 1rem;")
a("  --u-tile-border: 1px solid rgba(255, 255, 255, 0.14);")
a("  --u-tile-frame-border: 1px solid rgba(255, 255, 255, 0.12);")
a("  --u-tile-bg: rgba(255, 255, 255, 0.055);")
a("  --u-tile-frame-bg: rgba(0, 0, 0, 0.34);")
a("  --u-tile-shadow: 0 18px 50px rgba(0, 0, 0, 0.24);")
a("}")
a("")
a(".u-tile {")
a("  box-sizing: border-box;")
a("  padding: var(--u-tile-pad);")
a("  border-radius: var(--u-tile-radius);")
a("  border: var(--u-tile-border);")
a("  background: var(--u-tile-bg);")
a("  box-shadow: var(--u-tile-shadow);")
a("  overflow: hidden;")
a("}")
a("")
a(".u-tile-head {")
a("  margin: 0 0 var(--u-tile-pad-compact);")
a("}")
a("")
a(f".u-tile-head {gt} :first-child {{")
a("  margin-top: 0;")
a("}")
a("")
a(f".u-tile-head {gt} :last-child {{")
a("  margin-bottom: 0;")
a("}")
a("")
a(".u-tile-frame {")
a("  box-sizing: border-box;")
a("  width: fit-content;")
a("  max-width: 100%;")
a("  margin-inline: auto;")
a("  padding: var(--u-tile-pad-compact);")
a("  border-radius: var(--u-tile-frame-radius);")
a("  border: var(--u-tile-frame-border);")
a("  background: var(--u-tile-frame-bg);")
a("  overflow: hidden;")
a("  line-height: 0;")
a("}")
a("")
a(f".u-tile-frame {gt} iframe,")
a(f".u-tile-frame {gt} img,")
a(f".u-tile-frame {gt} video {{")
a("  display: block;")
a("  max-width: 100%;")
a("  margin: 0;")
a("  border: 0;")
a("}")
a("")
a("/* Universal tile aliases for existing card-like components */")
a(".tile,")
a(".content-card,")
a(".event-card,")
a(".stat-card,")
a(".social-card,")
a(".gallery-item,")
a(".cta-card,")
a(".faq-item,")
a(".notice-card,")
a(".sponsor-card,")
a(".timeline-item,")
a(".committee-crop-card {")
a("  box-sizing: border-box;")
a("}")
a("")
a(".tile,")
a(".content-card,")
a(".event-card,")
a(".stat-card,")
a(".social-card,")
a(".gallery-item,")
a(".cta-card,")
a(".faq-item,")
a(".notice-card,")
a(".sponsor-card {")
a("  border-radius: var(--u-tile-radius);")
a("}")
a("")
a(".gallery-item img,")
a(".card-photo,")
a(".committee-crop-image-frame {")
a("  border-radius: var(--u-tile-frame-radius);")
a("}")

p.write_text(text + "\n" + "\n".join(lines) + "\n")
print("Added UNIVERSAL TILE SYSTEM V1.")
