from pathlib import Path

p = Path("_includes/embed.html")
lines = []
a = lines.append
a('<section id="{{ include.section_id }}" class="section section-embed apple-panel" data-section-type="embed">')
a('  <div class="container">')
a('    {% include section-heading.html')
a('      eyebrow=include.section.eyebrow')
a('      title=include.section.title')
a('      subtitle=include.section.subtitle')
a('      alignment=include.section.alignment')
a('    %}')
a('')
a('    {% if include.section.id == "social-widgets" and include.section.embeds %}')
a('      {% assign facebook_embed = include.section.embeds | first %}')
a('')
a('      <div class="social-widget-grid">')
a('        <article class="u-tile social-widget-tile social-widget-facebook">')
a('          <header class="u-tile-head social-widget-head">')
a('            {% if facebook_embed.provider %}<p class="card-label">{{ facebook_embed.provider }}</p>{% endif %}')
a('            {% if facebook_embed.title %}<h3>{{ facebook_embed.title }}</h3>{% endif %}')
a('            {% if facebook_embed.description %}<p>{{ facebook_embed.description }}</p>{% endif %}')
a('          </header>')
a('')
a('          {% if facebook_embed.embed_html %}')
a('            <div class="u-tile-frame social-widget-frame social-widget-frame-facebook">')
a('              {{ facebook_embed.embed_html }}')
a('            </div>')
a('          {% endif %}')
a('')
a('          {% if facebook_embed.url %}')
a('            <div class="social-widget-mobile-cta">')
a('              {{ facebook_embed.url }}')
a('                {{ facebook_embed.button_label | default: "Open Facebook" }}')
a('              </a>')
a('            </div>')
a('          {% endif %}')
a('        </article>')
a('')
a('        <div class="social-widget-stack">')
a('          {% for embed in include.section.embeds offset:1 %}')
a('            <article class="u-tile social-widget-tile social-widget-strava">')
a('              <header class="u-tile-head social-widget-head">')
a('                {% if embed.provider %}<p class="card-label">{{ embed.provider }}</p>{% endif %}')
a('                {% if embed.title %}<h3>{{ embed.title }}</h3>{% endif %}')
a('                {% if embed.description %}<p>{{ embed.description }}</p>{% endif %}')
a('              </header>')
a('')
a('              {% if embed.embed_html %}')
a('                <div class="u-tile-frame social-widget-frame social-widget-frame-strava">')
a('                  {{ embed.embed_html }}')
a('                </div>')
a('              {% elsif embed.url %}')
a('                <div class="u-tile-frame social-widget-frame">')
a('                  {{ embed.url }}')
a('                    {{ embed.button_label | default: "Open" }}')
a('                  </a>')
a('                </div>')
a('              {% endif %}')
a('            </article>')
a('          {% endfor %}')
a('        </div>')
a('      </div>')
a('')
a('    {% elsif include.section.embeds %}')
a('      <div class="embed-grid embed-grid-{{ include.section.layout | default: \\'two\\' }}">')
a('        {% for embed in include.section.embeds %}')
a('          <article class="embed-shell embed-{{ embed.provider | default: \\'generic\\' }}">')
a('            <header class="embed-card-heading">')
a('              {% if embed.provider %}<p class="card-label">{{ embed.provider }}</p>{% endif %}')
a('              {% if embed.title %}<h3>{{ embed.title }}</h3>{% endif %}')
a('              {% if embed.description %}<p>{{ embed.description }}</p>{% endif %}')
a('            </header>')
a('            {% if embed.embed_html %}')
a('              <div class="embed-frame">{{ embed.embed_html }}</div>')
a('            {% elsif embed.url %}')
a('              <div class="embed-placeholder">')
a('                {{ embed.url }}')
a('                  {{ embed.button_label | default: "Open" }}')
a('                </a>')
a('              </div>')
a('            {% endif %}')
a('          </article>')
a('        {% endfor %}')
a('      </div>')
a('')
a('    {% else %}')
a('      <div class="embed-shell embed-{{ include.section.provider | default: \\'generic\\' }}">')
a('        {% if include.section.embed_html %}')
a('          <div class="embed-frame">{{ include.section.embed_html }}</div>')
a('        {% else %}')
a('          <div class="embed-placeholder"><p>Embed not configured yet.</p></div>')
a('        {% endif %}')
a('      </div>')
a('    {% endif %}')
a('  </div>')
a('</section>')

p.write_text("\\n".join(lines) + "\\n")
print("Rewrote embed include cleanly.")
